services:
  nginx-inject-service-worker:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./music-assistant-sw.js:/usr/share/nginx/html/music-assistant-sw.js
      - ./nginx-logs:/var/log/nginx
    labels:

      - "traefik.enable=true"
      - "traefik.http.routers.music-assistant.rule=Host(`730op.synology.me`) && PathPrefix(`/music-assistant`)"
      - "traefik.http.routers.music-assistant.entrypoints=websecure"
      - "traefik.http.routers.music-assistant.middlewares=strip-music-assistant,auth-music@docker"
      - "traefik.http.routers.music-assistant.tls.certresolver=myresolver"
      - "traefik.http.middlewares.strip-music-assistant.stripPrefix.prefixes=/music-assistant"
      - "traefik.http.services.music-assistant.loadbalancer.server.port=80"
    networks:
      - webgateway
  ha-forward-oauth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ha-forward-oauth
    environment:
      - FLASK_APP=app/main.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - .:/usr/src/app
    networks:
      - webgateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-callback.rule=Host(`730op.synology.me`) && Path(`/music-assistant/callback`)"
      - "traefik.http.routers.auth-callback.entrypoints=websecure"
      - "traefik.http.routers.auth-callback.tls.certresolver=myresolver"
      - "traefik.http.routers.auth-callback.middlewares=auth-callback-stripprefix"
      - "traefik.http.middlewares.auth-callback-stripprefix.stripprefix.prefixes=/music-assistant"
      - "traefik.http.services.ha-forward-oauth.loadbalancer.server.port=5000"
      - "traefik.http.middlewares.auth-music.forwardAuth.address=http://ha-forward-oauth:5000/auth"
networks:
  webgateway:
    external: true
